; This file was auto-generated by drush make
core = 7.x
api = 2

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ec_distro][download][type] = ""
projects[ec_distro][download][url] = ""
projects[ec_distro][type] = "profile"

; Modules
projects[] = views_bulk_operations
projects[] = admin_views
projects[] = ctools
projects[] = context
projects[] = draggableviews
projects[] = entity
projects[] = feature_basic_config
projects[] = feature_basic_content
projects[] = features
projects[] = field_collection
projects[] = field_group
projects[] = media
projects[] = wysiwyg

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[context][subdir] = "contrib"
projects[context][version] = "3.2"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][version] = "2.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[feature_basic_config][download][type] = ""
projects[feature_basic_config][download][url] = ""
projects[feature_basic_config][type] = "module"
projects[feature_basic_config][subdir] = "features/basic_setup"
projects[feature_basic_config][version] = "1.05"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[feature_basic_content][download][type] = ""
projects[feature_basic_content][download][url] = ""
projects[feature_basic_content][type] = "module"
projects[feature_basic_content][subdir] = "features/basic_setup"
projects[feature_basic_content][version] = "1.05"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta7"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[field_slideshow][subdir] = "contrib"
projects[field_slideshow][version] = "1.82"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha3"

projects[insert_view][subdir] = "contrib"
projects[insert_view][version] = "2.0"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-alpha3+108-dev"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][version] = "3.6"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2+46-dev"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tests][download][type] = ""
projects[tests][download][url] = ""
projects[tests][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[image_style_preview][download][type] = ""
projects[image_style_preview][download][url] = ""
projects[image_style_preview][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[insert_view_gen][download][type] = ""
projects[insert_view_gen][download][url] = ""
projects[insert_view_gen][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[media_display_migrate][download][type] = ""
projects[media_display_migrate][download][url] = ""
projects[media_display_migrate][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[media_displays][download][type] = ""
projects[media_displays][download][url] = ""
projects[media_displays][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[menu_block_placement][download][type] = ""
projects[menu_block_placement][download][url] = ""
projects[menu_block_placement][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[node_expanded_menu][download][type] = ""
projects[node_expanded_menu][download][url] = ""
projects[node_expanded_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pantheon_apachesolr][download][type] = ""
projects[pantheon_apachesolr][download][url] = ""
projects[pantheon_apachesolr][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pantheon_api][download][type] = ""
projects[pantheon_api][download][url] = ""
projects[pantheon_api][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pantheon_login][download][type] = ""
projects[pantheon_login][download][url] = ""
projects[pantheon_login][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[psr_0_test][download][type] = ""
projects[psr_0_test][download][url] = ""
projects[psr_0_test][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

