; This file was auto-generated by drush make
core = 7.x
api = 2

; Modules

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][type] = "module"
projects[views_bulk_operations][version] = "3.2"

projects[admin_views][subdir] = "contrib"
projects[admin_views][type] = "module"
projects[admin_views][version] = "1.3"

projects[ctools][subdir] = "contrib"
projects[ctools][type] = "module"
projects[ctools][version] = "1.4"

projects[context][subdir] = "contrib"
projects[context][type] = "module"
projects[context][version] = "3.2"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][type] = "module"
projects[draggableviews][version] = "2.0"

projects[entity][subdir] = "contrib"
projects[entity][type] = "module"
projects[entity][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][type] = "module"
projects[features][version] = "2.2"

projects[field_collection][subdir] = "contrib"
projects[field_collection][type] = "module"
projects[field_collection][version] = "1.0-beta7"

projects[field_group][subdir] = "contrib"
projects[field_group][type] = "module"
projects[field_group][version] = "1.4"

projects[field_slideshow][subdir] = "contrib"
projects[field_slideshow][type] = "module"
projects[field_slideshow][version] = "1.82"

projects[file_entity][subdir] = "contrib"
projects[file_entity][type] = "module"
projects[file_entity][version] = "2.0-alpha3"

projects[insert_view][subdir] = "contrib"
projects[insert_view][type] = "module"
projects[insert_view][version] = "2.0"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][type] = "module"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][type] = "module"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][type] = "module"
projects[link][version] = "1.2"

projects[media][subdir] = "contrib"
projects[media][type] = "module"
projects[media][version] = "2.x-dev"

projects[menu_block][subdir] = "contrib"
projects[menu_block][type] = "module"
projects[menu_block][version] = "2.4"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][type] = "module"
projects[quicktabs][version] = "3.6"

projects[strongarm][subdir] = "contrib"
projects[strongarm][type] = "module"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][type] = "module"
projects[views][version] = "3.8"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][type] = "module"
projects[wysiwyg][version] = "2.x-dev"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

