<?php
/**
 * @file
 * Code for the Feature Basic Content feature.
 */

include_once 'feature_basic_content.features.inc';

/*
 * Implements hook_views_query_alter().
 */
function feature_basic_content_views_query_alter(&$view, &$query) {
  if ($view->name == 'draggable_views') {
    $query->where[] = $query->where[1];
    $query->where[2]['conditions'][0]['value'] = '0';

    $query->where[1]['conditions'][] = $query->where[0]['conditions'][0];
    $query->where[2]['conditions'][] = $query->where[0]['conditions'][0];

    $query->where[1]['conditions'][] = $query->where[0]['conditions'][2];
    $query->where[2]['conditions'][] = $query->where[0]['conditions'][1];

    unset($query->where[0]);
  }
}

/*
 * Implements hook_flush_caches().
 */
function feature_basic_content_flush_caches() {
  //reset available regions
  _menu_block_placement_regions();
  $regions = variable_get('menu_block_placement_regions');
  $quicktabs = NULL;
  $context = NULL;

  //exporeted quicktabs and context
  include('includes/quicktabs.inc');
  include('includes/context.inc');

  //deletes a context and quicktabs if the region has been disabled within the theme
  foreach (quicktabs_block_info() as $key => $value) {
    if (substr($key, 0, 8) == 'dragview' && !array_key_exists(substr($key, 9), $regions)) {
      quicktabs_delete($key);
    }
  }
  foreach (context_load() as $key => $object) {
    if (substr($key, 0, 8) == 'dragview' && !array_key_exists(substr($key, 9), $regions)) {
      context_delete(context_load($key));
    }
  }

  //quicktabs and context for enabled regions.
  foreach ($regions as $key => $label) {
    //creates the quicktabs instance for the needed region
    $quicktabs->machine_name = 'dragview_' . $key;
    $quicktabs->title = 'Draggable Views ' . $label;
    $quicktabs->tabs[0]['args'] = $key;
    $quicktabs->tabs[1]['args'] = $key;
    quicktabs_save($quicktabs);

    //creates the context needed for the quicktabs created above.
    $context->name = 'dragview_' . $key;
    $context->description = ' Basic Blocks for the \'' . $label . '\' Region';
    $context->reactions['block']['blocks'] = array(
      'quicktabs-dragview_' . $key => array(
        'module' => 'quicktabs',
        'delta' => 'dragview_' . $key,
        'region' => $key,
        'weight' => '10',
      ),
    );
    context_save($context);
  }
}

/**
 * Implements hook_node_delete()
 *
 * The draggableviews_hanlder_fieldapi.inc doesn't delete draggable view entries out of its table,
 * this function cleans out those entries to nodes that don't exist.
 */
function feature_basic_content_node_delete($node) {
  db_delete('draggableviews_structure')
    ->condition('entity_id', $node->nid)
    ->execute();
}