<?php
/**
 * @file
 * Code for the Feature Basic Content feature.
 */

include_once 'feature_basic_content.features.inc';

/*
 * Implements hook_views_query_alter().
 */
function feature_basic_content_views_query_alter(&$view, &$query) {
  if ($view->name == 'draggable_views') {
    $query->where[] = $query->where[1];
    $query->where[2]['conditions'][0]['value'] = '0';

    $query->where[1]['conditions'][] = $query->where[0]['conditions'][0];
    $query->where[2]['conditions'][] = $query->where[0]['conditions'][0];

    $query->where[1]['conditions'][] = $query->where[0]['conditions'][2];
    $query->where[2]['conditions'][] = $query->where[0]['conditions'][1];

    unset($query->where[0]);
  }
}