<?php
/**
 * @file
 * feature_basic_workbench_config.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function feature_basic_workbench_config_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_content_section'
  $field_bases['field_content_section'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_content_section',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'sections',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  return $field_bases;
}
